<a href="https://colab.research.google.com/github/swathikuppusamy/Machine-Learning-Systima-NX-/blob/main/EmployeeAttrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
from google.colab import files
uploaded = files.upload()

Saving employee_attrition_dataset.csv to employee_attrition_dataset.csv

In [13]:
import io

df = pd.read_csv(io.BytesIO(uploaded['employee_attrition_dataset.csv']))
df.head()

,EmployeeID,Age,Gender,MaritalStatus,Education,Department,JobRole,YearsAtCompany,YearsInCurrentRole,MonthlyIncome,JobSatisfaction,WorkLifeBalance,TrainingTimesLastYear,OverTime,DistanceFromHome,Attrition
0,1,54,Male,Single,PhD,Sales,Analyst,17,12,19618.16,2,3,3,No,27.77,No
1,2,47,Male,Married,Master,Finance,Technician,32,7,7958.49,4,2,9,No,43.56,No
2,3,41,Female,Married,Master,Sales,Manager,37,7,10839.85,3,2,2,Yes,25.76,Yes
3,4,29,Male,Divorced,High School,IT,Manager,3,18,14488.44,5,2,4,Yes,25.11,Yes
4,5,37,Female,Divorced,High School,IT,Developer,25,12,9591.07,3,1,7,No,2.87,Yes

In [14]:
df.drop('EmployeeID',axis=1,inplace=True)
df.drop('Education',axis=1,inplace=True)

In [15]:
df

,Age,Gender,MaritalStatus,Department,JobRole,YearsAtCompany,YearsInCurrentRole,MonthlyIncome,JobSatisfaction,WorkLifeBalance,TrainingTimesLastYear,OverTime,DistanceFromHome,Attrition
0,54,Male,Single,Sales,Analyst,17,12,19618.16,2,3,3,No,27.77,No
1,47,Male,Married,Finance,Technician,32,7,7958.49,4,2,9,No,43.56,No
2,41,Female,Married,Sales,Manager,37,7,10839.85,3,2,2,Yes,25.76,Yes
3,29,Male,Divorced,IT,Manager,3,18,14488.44,5,2,4,Yes,25.11,Yes
4,37,Female,Divorced,IT,Developer,25,12,9591.07,3,1,7,No,2.87,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,60,Male,Married,Finance,Analyst,12,17,3584.92,4,5,0,Yes,28.54,Yes
4996,29,Male,Divorced,Finance,Developer,23,14,8898.45,3,2,3,No,47.10,No
4997,37,Male,Divorced,IT,Sales Executive,28,14,9408.65,1,3,6,No,43.61,No
4998,38,Male,Married,IT,Sales Executive,12,8,13497.24,4,4,2,No,30.48,No
4999,26,Male,Single,R&D,Sales Executive,2,18,15394.57,5,2,5,Yes,24.50,Yes

In [16]:
df.isnull().any()

Age                      False
Gender                   False
MaritalStatus            False
Department               False
JobRole                  False
YearsAtCompany           False
YearsInCurrentRole       False
MonthlyIncome            False
JobSatisfaction          False
WorkLifeBalance          False
TrainingTimesLastYear    False
OverTime                 False
DistanceFromHome         False
Attrition                False
dtype: bool

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [19]:
df.Gender=le.fit_transform(df.Gender)
df.MaritalStatus=le.fit_transform(df.MaritalStatus)
df.Department=le.fit_transform(df.Department)
df.JobRole=le.fit_transform(df.JobRole)
df.OverTime=le.fit_transform(df.OverTime)

In [20]:
df.Attrition=le.fit_transform(df.Attrition)

In [21]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
ats=['Age','MonthlyIncome', 'DistanceFromHome']
min_max_scaler = MinMaxScaler()
df[ats] = min_max_scaler.fit_transform(df[ats])

In [22]:
df.YearsAtCompany.max()

39

In [23]:
X=df.iloc[:,:14]
y=df.iloc[:,-1]
y

0       0
1       0
2       1
3       1
4       1
       ..
4995    1
4996    0
4997    0
4998    0
4999    1
Name: Attrition, Length: 5000, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 25,random_state = 46)

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc_knn = round(accuracy_score(y_pred,y_test), 2) * 100
print("Accuracy :" ,acc_knn)

Accuracy : 60.0

In [27]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb = XGBClassifier().fit(X_train, y_train)
y_pred = xgb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {round(accuracy * 100, 2)}%")

Accuracy: 100.0%